In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

import acquire as ac
import prepare as pr

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = ac.get_titanic_data()
df.head()

passenger_id  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500   
1             1         1       1  female  38.0      1      0  71.2833   
2             2         1       3  female  26.0      0      0   7.9250   
3             3         1       1  female  35.0      1      0  53.1000   
4             4         0       3    male  35.0      0      0   8.0500   

  embarked  class  deck  embark_town  alone  
0        S  Third  None  Southampton      0  
1        C  First     C    Cherbourg      0  
2        S  Third  None  Southampton      1  
3        S  First     C  Southampton      0  
4        S  Third  None  Southampton      1

In [3]:
train, test = pr.prep_titanic(df)
train.head()

passenger_id  survived  pclass     sex       age  sibsp  parch      fare  \
212           212         0       3    male  0.271174      0      0  0.014151   
222           222         0       3    male  0.635587      0      0  0.015713   
775           775         0       3    male  0.220910      0      0  0.015127   
229           229         0       3  female  0.346569      3      1  0.049708   
751           751         1       3    male  0.070118      0      1  0.024350   

     embarked  class  deck  embark_town  alone  
212         2  Third  None  Southampton      1  
222         2  Third  None  Southampton      1  
775         2  Third  None  Southampton      1  
229         2  Third  None  Southampton      0  
751         2  Third     E  Southampton      0

In [4]:
train.shape

(712, 13)

In [5]:
test.head()

passenger_id  survived  pclass   sex       age  sibsp  parch      fare  \
784           784         0       3  male  0.308872      0      0  0.013761   
382           382         0       3  male  0.396833      0      0  0.015469   
263           263         0       1  male  0.497361      0      0  0.000000   
647           647         1       1  male  0.698417      0      0  0.069291   
238           238         0       2  male  0.233476      0      0  0.020495   

     embarked   class  deck  embark_town  alone  
784         2   Third  None  Southampton      1  
382         2   Third  None  Southampton      1  
263         2   First     B  Southampton      1  
647         0   First     A    Cherbourg      1  
238         2  Second  None  Southampton      1

In [6]:
test.shape

(179, 13)

In [7]:
X_train = train[["fare", "pclass"]]
y_train = train[["survived"]]
X_test = test[["fare", "pclass"]]
y_test = test[["survived"]]

In [8]:
LogisticRegression?

In [9]:
# make the object
logit = LogisticRegression()

In [10]:
# fit the object
logit.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
logit.predict(X_train)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,

In [12]:
logit.predict_proba(X_train)

array([[0.74409806, 0.25590194],
       [0.74378116, 0.25621884],
       [0.74390003, 0.25609997],
       ...,
       [0.74397925, 0.25602075],
       [0.74390003, 0.25609997],
       [0.38363301, 0.61636699]])

> The probability for survival is shaped in this way because the LogisticRegression model is predicting the probabily of survival based on the two features in X_train

In [13]:
logit.score(X_train, y_train)

0.672752808988764

In [14]:
logit.score(X_test, y_test)

0.7039106145251397

In [15]:
y_pred = logit.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.88      0.79       110
           1       0.69      0.42      0.52        69

    accuracy                           0.70       179
   macro avg       0.70      0.65      0.65       179
weighted avg       0.70      0.70      0.68       179

